apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stream-to-adw-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: stream-to-adw  
    spec:     # pod spec                  
      containers: 
      - name: stream-to-adw
        image: fra.ocir.io/orasealps/wuzzler/stream-to-adw:1.0 # image we pushed
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: ocirkey

---
apiVersion: v1
kind: Service
metadata:
  name: stream-to-adw-svc
spec:
  selector:
    app: stream-to-adw
  ports:
    - port: 8089
      targetPort: 8081
  type: ClusterIP
